
  url: https://www.google.com/client_204
  interval: 60
  type: url-test
  tolerance: 100

dns:
  enable: false # set true to enable dns (default is false)
  ipv6: false # default is false
  listen: 0.0.0.0:54
  enhanced-mode: redir-host
  nameserver:
     - 127.0.0.1
     - 223.5.5.5
     - 1.2.4.8
  fallback:
     - https://1.1.1.1/dns-query


rules:
- DOMAIN-SUFFIX,doubleclick.net,REJECT
- DOMAIN-SUFFIX,googleadservices.com,REJECT
- DOMAIN-SUFFIX,googleadsserving.cn,REJECT
- DOMAIN-SUFFIX,googlesyndication.com,REJECT

- GEOIP,CN,DIRECT

- MATCH,,AUTO
allow-lan: true
external-controller: 127.0.0.1:9090
log-level: warning
mode: rule
port: 7890
socks-port: 7891
